- name: Install Kibana .deb package
  hosts: kibana 
  become: true
  vars:
    kibana_deb_url: "https://artifacts.elastic.co/downloads/kibana/kibana-9.0.3-amd64.deb"
    kibana_deb_file: "/tmp/kibana.deb"

  tasks:
    - name: Ensure dependencies are installed
      apt:
        name: wget
        state: present
        update_cache: true

    - name: Download Kibana .deb package
      get_url:
        url: "{{ kibana_deb_url }}"
        dest: "{{ kibana_deb_file }}"
        mode: '0644'

    - name: Install Kibana .deb package
      apt:
        deb: "{{ kibana_deb_file }}"
        state: present

