- name: Generate Nginx reverse proxy configs
  hosts: questions
  become: true
  vars:
    teams:
      - team1
      - team2
    questions:
      - example1
      - example2
    domain_suffix: ctf
    question_ports:
      example1: 9001
      example2: 9002

  tasks:
    - name: Generate Nginx config for each team-question
      ansible.builtin.template:
        src: templates/nginx-reverseproxy.conf.j2
        dest: "/etc/nginx/sites-available/{{ item.0 }}.{{ item.1 }}.{{ domain_suffix }}"
        mode: "0644"
      loop: "{{ teams | product(questions) | list }}"
      vars:
        backend_port: "{{ question_ports[item.1] }}"

    - name: Enable Nginx sites
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item.0 }}.{{ item.1 }}.{{ domain_suffix }}"
        dest: "/etc/nginx/sites-enabled/{{ item.0 }}.{{ item.1 }}.{{ domain_suffix }}"
        state: link
        force: true
      loop: "{{ teams | product(questions) | list }}"

    - name: Reload Nginx
      systemd:
        name: nginx
        state: restarted
