- name: Install CTF Dependecies
  hosts: master:vpn:questions
  tasks:
    - name: Update repository
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade Packages
      apt:
        upgrade: full
    - name: Install Packages
      apt:
        name:
          - wireguard
          - ca-certificates
          - curl
          - podman
