- name: Install CTF Dependecies
  hosts: master:vpn:docker
  tasks:
    - name: Remove docker repositories
      ansible.builtin.shell:
        rm -f /etc/apt/sources.list.d/docker.list
    - name: Update Repositories 
      apt:
        update_cache: true
    - name: Install keyrings
      ansible.builtin.command:
        sudo install -m 0755 -d /etc/apt/keyrings
    - name: Install Docker keyrings
      ansible.builtin.command:
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - name: Set Docker keyring permissions
      ansible.builtin.command:
        sudo chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add Docker APT repository to sources.list.d
      become: true
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" \
        | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Update repository
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - wireguard
          - ca-certificates
          - curl
