- name: Install CTF Dependecies
  hosts: master:vpn:questions
  tasks:
    - name: Update repository
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        name:
          - wireguard
          - ca-certificates
          - curl
          - podman
