- name: CTF Subdomain Zone Generator
  hosts: master
  become: true
  vars:
    teams:
      - team1
      - team2
    questions:
      - example1
      - example2
    domain_suffix: "ctf"
    questions_ip: "{{ hostvars[groups['questions'][0]]['vpn_ip'] }}"

  tasks:
    - name: Create named.conf.zones with all subdomains
      ansible.builtin.template:
        src: templates/named-zones.conf.j2
        dest: /etc/bind/named.conf.zones
        owner: root
        group: bind
        mode: "0644"

    - name: Create zone files
      ansible.builtin.template:
        src: templates/db.zone.j2
        dest: "/etc/bind/zones/db.{{ item.0 }}.{{ item.1 }}.{{ domain_suffix }}"
        owner: root
        group: bind
        mode: "0644"
      loop: "{{ teams | product(questions) | list }}"
    - name: Restart bind9
      systemd:
        name: bind9
        state: restarted
